/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lights_out_gomez_el_addouli;

import java.util.Random;

/**
 *
 * @author sarah
 */
public class fenetreDeJeu extends javax.swing.JFrame {

    Grille GrilleJeu = new Grille();

    /**
     * Creates new form fenetreDeJeu
     */
    public fenetreDeJeu() {
        initComponents();

        for (int ligne = 4; ligne >= 0; ligne--) {
            for (int col = 0; col < 5; col++) {
                CelluleGraphique cellGraph = new CelluleGraphique(GrilleJeu.Case[ligne][col]);

                cellGraph.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        
                        Cellules c = cellGraph.CelluleAssociee; // c cellule de la grille de jeu associé au bouton sur lequel on clique
                        
                        jTextArea3.setText("truc");// juste de la vérification A SUPPRIMER 
                        
                        
                        
                        panneau_grille.repaint(); 
                    }
                });

                panneau_grille.add(cellGraph);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textemessage = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        panneau_grille = new javax.swing.JPanel();
        panneau_titre = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panneau_creation_partie = new javax.swing.JPanel();
        btn_start = new javax.swing.JButton();
        panneau_chrono = new javax.swing.JPanel();
        truc = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        panneau_nb_coups = new javax.swing.JPanel();
        panneau_regles = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jLabel1.setText("jLabel1");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        textemessage.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneau_grille.setBackground(new java.awt.Color(153, 102, 255));
        panneau_grille.setLayout(new java.awt.GridLayout(5, 5));
        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 500, 500));

        panneau_titre.setBackground(new java.awt.Color(204, 204, 255));
        panneau_titre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Academy Engraved LET", 1, 36)); // NOI18N
        jLabel2.setText("Lights Out");
        panneau_titre.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, -1));

        getContentPane().add(panneau_titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 400, 60));

        panneau_creation_partie.setBackground(new java.awt.Color(204, 204, 255));
        panneau_creation_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_start.setText("Démarrer partie");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        panneau_creation_partie.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 200, 70));

        getContentPane().add(panneau_creation_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 400, 90));

        panneau_chrono.setBackground(new java.awt.Color(204, 204, 255));
        panneau_chrono.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        truc.setViewportView(jTextArea3);

        panneau_chrono.add(truc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, -1));

        getContentPane().add(panneau_chrono, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 130, 130));

        panneau_nb_coups.setBackground(new java.awt.Color(204, 204, 255));
        panneau_nb_coups.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panneau_nb_coups, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, 130, 130));

        panneau_regles.setBackground(new java.awt.Color(204, 204, 255));
        panneau_regles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("But du Jeu : \nAvoir une grille avec toute les cases éteintes en un \nminimum de temps.  \n\nRègles : \nLorsque l'on appuie sur une case, celle-ci ainsi que les\ncases adjacente, excepté les diagonales, changent de \npolarité (les cases éteintes s'allument et les cases allumées\ns'éteignent).");
        jScrollPane1.setViewportView(jTextArea1);

        panneau_regles.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 150));

        getContentPane().add(panneau_regles, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 400, 170));

        setBounds(0, 0, 1000, 628);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed

        InitialiserPartie();

        panneau_grille.repaint();// rafraichit l'affichage 

        btn_start.setEnabled(false); // on ne peut pas cliquer plusieurs fois sur le btn Démarrer partie

    }//GEN-LAST:event_btn_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetreDeJeu().setVisible(true);
            }
        });
    }

    public void InitialiserPartie() {
        Random nbAleatoire = new Random();
        int CaseDeb = 1 + nbAleatoire.nextInt(12);
        for (int i = 0; i <= CaseDeb; i++) {
            int ligneAlea = nbAleatoire.nextInt(4);
            int ColAlea = nbAleatoire.nextInt(4);
            GrilleJeu.SwitchEtat(ligneAlea, ColAlea);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JPanel panneau_chrono;
    private javax.swing.JPanel panneau_creation_partie;
    private javax.swing.JPanel panneau_grille;
    private javax.swing.JPanel panneau_nb_coups;
    private javax.swing.JPanel panneau_regles;
    private javax.swing.JPanel panneau_titre;
    private javax.swing.JScrollPane textemessage;
    private javax.swing.JScrollPane truc;
    // End of variables declaration//GEN-END:variables
}
