/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lights_out_gomez_el_addouli;

import java.awt.event.ActionEvent;
import java.util.Random;
import java.util.Scanner;

/**
 *
 * @author sarah
 */
public class fenetreDeJeu extends javax.swing.JFrame {

    Grille GrilleJeu = new Grille();
    Partie P = new Partie();
    CelluleGraphique[][] tab = new CelluleGraphique[5][5];

    /**
     * Creates new form fenetreDeJeu
     */
    public fenetreDeJeu() {
        initComponents();

        for (int ligne = 4; ligne >= 0; ligne--) {
            for (int col = 0; col < 5; col++) {

                int a = ligne;
                int b = col;
                CelluleGraphique cellGraph = new CelluleGraphique(GrilleJeu.Case[ligne][col]);

                tab[ligne][col] = cellGraph;
                tab[ligne][col].setEnabled(false);

                cellGraph.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {

                        Cellules c = cellGraph.CelluleAssociee; // c cellule de la grille de jeu associé au bouton sur lequel on clique

                        DebuterPartie(a, b);

                        jTextArea3.setText("La cellule a été sélectionnée.");// juste de la vérification A SUPPRIMER 

                        panneau_grille.repaint();
                        if (GrilleJeu.GrilleEteinte() == true) {
                            jTextArea3.setText("Victoire !");

                            for (int ligne = 4; ligne >= 0; ligne--) {
                                for (int col = 0; col < 5; col++) {
                                    tab[ligne][col].setEnabled(false);
                                }
                            }
                        }
                    }
                });

                panneau_grille.add(cellGraph);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textemessage = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        panneau_grille = new javax.swing.JPanel();
        panneau_titre = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panneau_creation_partie = new javax.swing.JPanel();
        btn_start = new javax.swing.JButton();
        panneau_chrono = new javax.swing.JPanel();
        truc = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        chrono = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panneau_regles = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jLabel1.setText("jLabel1");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        textemessage.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneau_grille.setBackground(new java.awt.Color(153, 102, 255));
        panneau_grille.setLayout(new java.awt.GridLayout(5, 5));
        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 500, 500));

        panneau_titre.setBackground(new java.awt.Color(204, 204, 255));
        panneau_titre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panneau_titre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Academy Engraved LET", 1, 36)); // NOI18N
        jLabel2.setText("Lights Out");
        panneau_titre.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 170, -1));

        getContentPane().add(panneau_titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 400, -1));

        panneau_creation_partie.setBackground(new java.awt.Color(204, 204, 255));
        panneau_creation_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_start.setText("Démarrer partie");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        panneau_creation_partie.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 190, 60));

        getContentPane().add(panneau_creation_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 400, 80));

        panneau_chrono.setBackground(new java.awt.Color(204, 204, 255));
        panneau_chrono.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        truc.setViewportView(jTextArea3);

        panneau_chrono.add(truc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, -1));

        getContentPane().add(panneau_chrono, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 400, 110));

        chrono.setBackground(new java.awt.Color(204, 204, 255));
        chrono.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        chrono.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chrono.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 30, 30));

        jPanel3.setBackground(new java.awt.Color(153, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chrono.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel4.setText("Case allumée");
        chrono.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel5.setText("Case éteinte");
        chrono.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        getContentPane().add(chrono, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 400, 50));

        panneau_regles.setBackground(new java.awt.Color(204, 204, 255));
        panneau_regles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("But du Jeu : \nAvoir une grille avec toute les cases éteintes (= violet foncé).\n\n\nRègles : \nLorsque l'on appuie sur une case, celle-ci ainsi que les\ncases adjacente, excepté les diagonales, changent de \npolarité (les cases éteintes s'allument et les cases allumées\ns'éteignent).\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        panneau_regles.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 150));

        getContentPane().add(panneau_regles, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 400, 170));

        setBounds(0, 0, 1000, 628);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        for (int ligne = 4; ligne >= 0; ligne--) {
            for (int col = 0; col < 5; col++) {
                tab[ligne][col].setEnabled(true);

            }

        }

        InitialiserPartie();

        panneau_grille.repaint();// rafraichit l'affichage 
        btn_start.setEnabled(false); // on ne peut pas cliquer plusieurs fois sur le btn Démarrer partie

    }//GEN-LAST:event_btn_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetreDeJeu().setVisible(true);
            }
        });
    }

    public void InitialiserPartie() {
        Random nbAleatoire = new Random();
        int CaseDeb = 1 + nbAleatoire.nextInt(12);
        for (int i = 0; i <= CaseDeb; i++) {
            int ligneAlea = nbAleatoire.nextInt(4);
            int ColAlea = nbAleatoire.nextInt(4);
            GrilleJeu.SwitchEtat(ligneAlea, ColAlea);
        }
    }

    public void DebuterPartie(int ligne, int col) {

        GrilleJeu.SwitchEtat(ligne, col);
        if (col == 0) {
            GrilleJeu.SwitchEtat(ligne, col + 1);
            if (ligne == 0) {
                GrilleJeu.SwitchEtat(ligne + 1, col);
            } else if (ligne == 4) {
                GrilleJeu.SwitchEtat(ligne - 1, col);
            } else {
                GrilleJeu.SwitchEtat(ligne - 1, col);
                GrilleJeu.SwitchEtat(ligne + 1, col);
            }
        } else if (col == 4) {
            GrilleJeu.SwitchEtat(ligne, col - 1);

            if (ligne == 0) {
                GrilleJeu.SwitchEtat(ligne + 1, col);
            } else if (ligne == 4) {
                GrilleJeu.SwitchEtat(ligne - 1, col);
            } else {
                GrilleJeu.SwitchEtat(ligne - 1, col);
                GrilleJeu.SwitchEtat(ligne + 1, col);
            }
        } else if (ligne == 4) {
            GrilleJeu.SwitchEtat(ligne - 1, col);
            GrilleJeu.SwitchEtat(ligne, col + 1);
            GrilleJeu.SwitchEtat(ligne, col - 1);
        } else if (ligne == 0) {
            GrilleJeu.SwitchEtat(ligne + 1, col);
            GrilleJeu.SwitchEtat(ligne, col + 1);
            GrilleJeu.SwitchEtat(ligne, col - 1);
        } else {
            GrilleJeu.SwitchEtat(ligne - 1, col);
            GrilleJeu.SwitchEtat(ligne + 1, col);
            GrilleJeu.SwitchEtat(ligne, col - 1);
            GrilleJeu.SwitchEtat(ligne, col + 1);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_start;
    private javax.swing.JPanel chrono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JPanel panneau_chrono;
    private javax.swing.JPanel panneau_creation_partie;
    private javax.swing.JPanel panneau_grille;
    private javax.swing.JPanel panneau_regles;
    private javax.swing.JPanel panneau_titre;
    private javax.swing.JScrollPane textemessage;
    private javax.swing.JScrollPane truc;
    // End of variables declaration//GEN-END:variables
}
